export const categories = [
  {
    sfw: true,
    name: "waifu",
    command: "waifu",
    description: "Get a random waifu!",
  },
  {
    sfw: true,
    name: "neko",
    command: "neko",
    description: "Get a random neko!",
  },
  {
    sfw: true,
    name: "shinobu",
    command: "shinobu",
    description: "Get a random shinobu!",
  },
  {
    sfw: true,
    name: "megumin",
    command: "megumin",
    description: "Get a random megumin!",
  },
  {
    sfw: true,
    name: "bully",
    command: "bully",
    description: "Get a random bully!",
  },
  {
    sfw: true,
    name: "cuddle",
    command: "cuddle",
    description: "Get a random cuddle!",
  },
  {
    sfw: true,
    name: "cry",
    command: "cry",
    description: "Get a random cry!",
  },
  {
    sfw: true,
    name: "hug",
    command: "hug",
    description: "Get a random hug!",
  },
  {
    sfw: true,
    name: "awoo",
    command: "awoo",
    description: "Get a random awoo!",
  },
  {
    sfw: true,
    name: "kiss",
    command: "kiss",
    description: "Get a random kiss!",
  },
  {
    sfw: true,
    name: "lick",
    command: "lick",
    description: "Get a random lick!",
  },
  {
    sfw: true,
    name: "pat",
    command: "pat",
    description: "Get a random pat!",
  },
  {
    sfw: true,
    name: "smug",
    command: "smug",
    description: "Get a random smug!",
  },
  {
    sfw: true,
    name: "bonk",
    command: "bonk",
    description: "Get a random bonk!",
  },
  {
    sfw: true,
    name: "yeet",
    command: "yeet",
    description: "Get a random yeet!",
  },
  {
    sfw: true,
    name: "blush",
    command: "blush",
    description: "Get a random blush!",
  },
  {
    sfw: true,
    name: "smile",
    command: "smile",
    description: "Get a random smile!",
  },
  {
    sfw: true,
    name: "wave",
    command: "wave",
    description: "Get a random wave!",
  },
  {
    sfw: true,
    name: "highfive",
    command: "highfive",
    description: "Get a random highfive!",
  },
  {
    sfw: true,
    name: "handhold",
    command: "handhold",
    description: "Get a random handhold!",
  },
  {
    sfw: true,
    name: "nom",
    command: "nom",
    description: "Get a random nom!",
  },
  {
    sfw: true,
    name: "bite",
    command: "bite",
    description: "Get a random bite!",
  },
  {
    sfw: true,
    name: "glomp",
    command: "glomp",
    description: "Get a random glomp!",
  },
  {
    sfw: true,
    name: "kill",
    command: "kill",
    description: "Get a random kill!",
  },
  {
    sfw: true,
    name: "slap",
    command: "slap",
    description: "Get a random slap!",
  },
  {
    sfw: true,
    name: "happy",
    command: "happy",
    description: "Get a random happy!",
  },
  {
    sfw: true,
    name: "wink",
    command: "wink",
    description: "Get a random wink!",
  },
  {
    sfw: true,
    name: "poke",
    command: "poke",
    description: "Get a random poke!",
  },
  {
    sfw: true,
    name: "dance",
    command: "dance",
    description: "Get a random dance!",
  },
  {
    sfw: true,
    name: "cringe",
    command: "cringe",
    description: "Get a random cringe!",
  },
  {
    sfw: false,
    name: "waifu",
    command: "nsfw-waifu",
    description: "Get a random waifu!",
  },
  {
    sfw: false,
    name: "neko",
    command: "nsfw-neko",
    description: "Get a random neko!",
  },
  {
    sfw: false,
    name: "trap",
    command: "nsfw-trap",
    description: "Get a random trap!",
  },
  {
    sfw: false,
    name: "blowjob",
    command: "nsfw-blowjob",
    description: "Get a random blowjob!",
  },
  {
    sfw: false,
    name: "help",
    command: "help",
    description: "Get some help",
  },
];
